version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - FIREBASE_CONFIG_PATH=/app/config/firebase-config.json
    volumes:
      - ./firebase-config.json:/app/config/firebase-config.json:ro